name: "Build docker image"
on:
  push:
    branches:
      - devnet
      - testnet
      - main
      - aptos-release-*
      - mamoru-testnet

env:
  CARGO_INCREMENTAL: "0"
  CARGO_TERM_COLOR: always
  REPOSITORY: mamorufoundation/aptos-sniffer
  TARGET: validator

concurrency:
  # cancel redundant builds on PRs (only on PR, not on branches)
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Start docker service
        run: sudo service docker start || true

      - uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: |
            ${{ secrets.MAMORU_CORE_KEY }}
            ${{ secrets.VALIDATION_CHAIN_KEY }}

      - name: Prepare git and ssh config for build context
        run: |
          mkdir root-config
          cp -r ~/.gitconfig ~/.ssh root-config/

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push validator image
        run: |
          TARGET_IMAGE_NAME="${{ env.REPOSITORY }}" \
          TARGET_IMAGE_TAG="${{ github.sha }}" \
          SSH_AUTH_SOCK=${{ env.SSH_AUTH_SOCK }} \
          GIT_CREDENTIALS="" \
          docker/builder/docker-bake-rust-all.sh ${{ env.TARGET }}
